spring:
  application:
    name: @project.name@
  data:
    mongodb:
      database: db
      uri: ${CONNECTION_STRING:mongodb://root:example@localhost:27017}
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#  level:
#    net.samitkumarpatel.webfluxmongocosmos.*: debug

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus

  endpoint:
    health:
      probes:
        enabled: true
